

----sE USA PARAEVALUAR UNA PORCION DE CODIGO EN LA QUE ESTAMOS ACTUALIZANDO DATOS O INSERT
select * from T_Paciente

BEGIN TRAN
   UPDATE T_Paciente SET Telefono=4450258 WHERE Apellido = 'CRUZ'

   IF @@ROWCOUNT = 1 --CUANTOS REGISTROS FUERON AFECTADOS
     COMMIT TRAN
   ELSE
     ROLLBACK TRAN --CANCELA EL BEGIN TRAN


SELECT * FROM T_Turno
SELECT * FROM T_TurnoEstado
SELECT * FROM T_TurnoPaciente
  